apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-ci-intel-supply-chain
  annotations:
    policies.kyverno.io/title: "CI Intelligence Hub Supply Chain Guardrails"
    policies.kyverno.io/category: Supply Chain
    policies.kyverno.io/minversion: 1.10.0
    policies.kyverno.io/description: >
      Ensures workloads only deploy the signed ghcr.io/jguida941/ci-intel-app image,
      validates its Sigstore keyless signature, and requires SLSA provenance plus SPDX
      and CycloneDX SBOM attestations that are published as OCI referrers during release.
spec:
  background: true
  validationFailureAction: Enforce
  failurePolicy: Fail
  webhookTimeoutSeconds: 10
  rules:
    - name: require-digest-pins
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
                - CronJob
              namespaces:
                - dev
                - staging
                - prod
      validate:
        message: "All containers must reference immutable image digests (@sha256)."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - image: "*@sha256:*"
                =(initContainers):
                  - image: "*@sha256:*"
    - name: verify-ci-intel-signature-and-attestations
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
                - CronJob
      verifyImages:
        - imageReferences:
            - "ghcr.io/jguida941/ci-intel-app:*"
            - "ghcr.io/jguida941/ci-intel-app@sha256:*"
          attestors:
            - count: 1
              entries:
                - keyless:
                    url: https://fulcio.sigstore.dev
                    issuer: "https://token.actions.githubusercontent.com"
                    subject: &github_workflow_identity "https://github.com/jguida941/ci-cd-bst-demo-github-actions/.github/workflows/release.yml@refs/*"
                  rekor:
                    url: https://rekor.sigstore.dev
                  annotations:
                    cosign.sigstore.dev/certificate-oidc-issuer: "https://token.actions.githubusercontent.com"
                    cosign.sigstore.dev/certificate-identity: *github_workflow_identity
                  attestation:
                    type: https://slsa.dev/provenance/v1
          attestations:
            - predicateType: https://slsa.dev/provenance/v1
            - predicateType: spdx
            - predicateType: cyclonedx
