apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-secretless-ci
  annotations:
    policies.kyverno.io/title: Enforce OIDC-only workloads
    policies.kyverno.io/description: >
      Deny Pods and higher-level controllers that attempt to mount secret-based credentials.
      Workloads must rely on ephemeral OIDC tokens minted at runtime; opt-out only via the
      ci-intel.dev/allow-static-secrets label.
spec:
  validationFailureAction: Enforce
  background: false
  failurePolicy: Fail
  rules:
    - name: disallow-secret-env-pods
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.\"ci-intel.dev/allow-static-secrets\" }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Use OIDC-issued tokens; env secretKeyRef and secret volumes are forbidden."
        deny:
          conditions:
            any:
              - key: "{{ length(request.object.spec.containers[].env[?valueFrom.secretKeyRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.initContainers[].env[?valueFrom.secretKeyRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?secret]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?projected.sources[?secret]]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?csi.nodePublishSecretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?csi.nodeStageSecretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?flexVolume.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?rbd.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?iscsi.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?cephfs.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.volumes[?scaleIO.secretRef]) }}"
                operator: GreaterThan
                value: 0
    - name: disallow-secret-env-controllers
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.\"ci-intel.dev/allow-static-secrets\" }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Controllers must not template secretKeyRef env vars or secret volumes."
        deny:
          conditions:
            any:
              - key: "{{ length(request.object.spec.template.spec.containers[].env[?valueFrom.secretKeyRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.initContainers[].env[?valueFrom.secretKeyRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?secret]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?projected.sources[?secret]]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?csi.nodePublishSecretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?csi.nodeStageSecretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?flexVolume.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?rbd.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?iscsi.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?cephfs.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.template.spec.volumes[?scaleIO.secretRef]) }}"
                operator: GreaterThan
                value: 0
    - name: disallow-secret-env-cronjobs
      match:
        any:
          - resources:
              kinds:
                - CronJob
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.\"ci-intel.dev/allow-static-secrets\" }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "CronJobs must not mount static secrets; rely on OIDC tokens."
        deny:
          conditions:
            any:
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.containers[].env[?valueFrom.secretKeyRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.initContainers[].env[?valueFrom.secretKeyRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?secret]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?projected.sources[?secret]]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?csi.nodePublishSecretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?csi.nodeStageSecretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?flexVolume.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?rbd.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?iscsi.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?cephfs.secretRef]) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.jobTemplate.spec.template.spec.volumes[?scaleIO.secretRef]) }}"
                operator: GreaterThan
                value: 0
