# ============================================================================
# Kyverno Policy: Secretless Workloads
# ============================================================================
# Blocks pods that use secrets as environment variables.
# Forces use of mounted secrets or external secret managers.
#
# Requirements:
#   - Kyverno installed in cluster
# ============================================================================

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: secretless-workloads
  annotations:
    policies.kyverno.io/title: Block secret environment variables
    policies.kyverno.io/category: Security Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >
      Prevents pods from using secrets as plain environment variables.
      Use mounted secrets or external secret managers instead.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: block-secret-env-vars
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              # Allow exceptions for specific namespaces
              namespaces:
                - kube-system
                - cert-manager
          - resources:
              selector:
                matchLabels:
                  # Label to opt-out (use sparingly)
                  allow-secret-env: "true"
      validate:
        message: >
          Secrets as environment variables are not allowed.
          Use volumeMounts with secret volumes instead, or use an
          external secrets manager. Add label 'allow-secret-env: true'
          to opt-out (requires approval).
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[*].env[*].valueFrom.secretKeyRef | length(@) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ request.object.spec.containers[*].envFrom[*].secretRef | length(@) }}"
                operator: GreaterThan
                value: 0
