#!/usr/bin/env bash
# Generate STRUCTURE.md from actual filesystem
# Hardened for portability - works without tree command

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/STRUCTURE.md"

log() {
  echo "[generate-structure] $*" >&2
}

# Check if tree command is available
if command -v tree &>/dev/null; then
  USE_TREE=true
  log "Using 'tree' command for structure generation"
else
  USE_TREE=false
  log "WARNING: 'tree' not found, falling back to find-based generation"
fi

# Generate structure using tree if available
generate_with_tree() {
  tree -L 3 \
    -I 'node_modules|.git|__pycache__|*.pyc|.pytest_cache|.venv|venv' \
    --charset ascii \
    --gitignore \
    --dirsfirst \
    "$REPO_ROOT"
}

# Fallback: generate structure using find
generate_with_find() {
  cd "$REPO_ROOT"

  # Print root
  echo "."

  # Find directories, limit depth to 3
  find . -maxdepth 3 -type d \
    ! -path "./.git*" \
    ! -path "*/node_modules*" \
    ! -path "*/__pycache__*" \
    ! -path "*/.pytest_cache*" \
    ! -path "*/.venv*" \
    ! -path "*/venv*" \
    | sort \
    | sed 's|^\./||' \
    | awk '{
        depth = gsub(/\//, "/");
        indent = "";
        for (i = 0; i < depth; i++) indent = indent "  ";
        name = $0;
        gsub(/^.*\//, "", name);
        if (name != "") print indent "├── " name "/";
      }'

  # Find files in top 3 levels
  find . -maxdepth 3 -type f \
    ! -path "./.git*" \
    ! -path "*/node_modules*" \
    ! -path "*/__pycache__*" \
    ! -path "*/.pytest_cache*" \
    ! -path "*/.venv*" \
    ! -path "*/venv*" \
    ! -name "*.pyc" \
    | sort \
    | sed 's|^\./||' \
    | awk '{
        depth = gsub(/\//, "/");
        indent = "";
        for (i = 0; i < depth; i++) indent = indent "  ";
        name = $0;
        gsub(/^.*\//, "", name);
        if (name != "") print indent "├── " name;
      }'
}

# Main execution
{
  echo "# Repository Structure"
  echo ""
  echo "Last updated: $(date +%Y-%m-%d) (auto-generated by scripts/docs/generate_structure.sh)"
  echo ""
  echo '```'

  if [[ "$USE_TREE" == "true" ]]; then
    if ! generate_with_tree; then
      log "ERROR: tree command failed, falling back to find"
      generate_with_find
    fi
  else
    generate_with_find
  fi

  echo '```'
  echo ""
  echo "See [docs/index.md](docs/index.md) for documentation index."
} > "$OUTPUT_FILE"

log "✅ Generated $OUTPUT_FILE"
