import argparse
from pathlib import Path

from cihub.cli import CommandResult
from cihub.commands.docs import _check_internal_links, cmd_docs


def test_docs_generate_writes_files(tmp_path: Path) -> None:
    args = argparse.Namespace(
        subcommand="generate",
        output=str(tmp_path),
        check=False,
        json=True,
    )
    result = cmd_docs(args)
    assert isinstance(result, CommandResult)
    assert result.exit_code == 0

    cli_path = tmp_path / "CLI.md"
    config_path = tmp_path / "CONFIG.md"
    assert cli_path.exists()
    assert config_path.exists()
    assert "Generated by `cihub docs generate`" in cli_path.read_text(encoding="utf-8")


def test_docs_check_ok(tmp_path: Path) -> None:
    generate_args = argparse.Namespace(
        subcommand="generate",
        output=str(tmp_path),
        check=False,
        json=True,
    )
    cmd_docs(generate_args)

    check_args = argparse.Namespace(
        subcommand="check",
        output=str(tmp_path),
        json=True,
    )
    result = cmd_docs(check_args)
    assert isinstance(result, CommandResult)
    assert result.exit_code == 0


def test_docs_check_detects_drift(tmp_path: Path) -> None:
    generate_args = argparse.Namespace(
        subcommand="generate",
        output=str(tmp_path),
        check=False,
        json=True,
    )
    cmd_docs(generate_args)

    (tmp_path / "CLI.md").write_text("corrupted", encoding="utf-8")

    check_args = argparse.Namespace(
        subcommand="check",
        output=str(tmp_path),
        json=True,
    )
    result = cmd_docs(check_args)
    assert isinstance(result, CommandResult)
    assert result.exit_code == 1


def test_internal_links_valid(tmp_path: Path) -> None:
    """Test that valid internal links pass."""
    (tmp_path / "README.md").write_text("See [guide](guide.md) for details.", encoding="utf-8")
    (tmp_path / "guide.md").write_text("# Guide", encoding="utf-8")

    problems = _check_internal_links(tmp_path)
    assert problems == []


def test_internal_links_broken(tmp_path: Path) -> None:
    """Test that broken internal links are detected."""
    (tmp_path / "README.md").write_text("See [missing](nonexistent.md) for details.", encoding="utf-8")

    problems = _check_internal_links(tmp_path)
    assert len(problems) == 1
    assert "nonexistent.md" in problems[0]["target"]
    assert problems[0]["code"] == "CIHUB-DOCS-BROKEN-LINK"


def test_internal_links_skips_external(tmp_path: Path) -> None:
    """Test that external links are skipped."""
    (tmp_path / "README.md").write_text(
        "See [GitHub](https://github.com) and [anchor](#section).",
        encoding="utf-8",
    )

    problems = _check_internal_links(tmp_path)
    assert problems == []


def test_internal_links_skips_code_blocks(tmp_path: Path) -> None:
    """Links inside fenced code blocks should be ignored."""
    (tmp_path / "README.md").write_text(
        "```md\nSee [missing](missing.md)\n```\n",
        encoding="utf-8",
    )

    problems = _check_internal_links(tmp_path)
    assert problems == []


def test_internal_links_reference_definitions(tmp_path: Path) -> None:
    """Reference-style link definitions should be checked."""
    (tmp_path / "README.md").write_text(
        "See [Guide][guide].\n\n[guide]: guide.md\n",
        encoding="utf-8",
    )
    (tmp_path / "guide.md").write_text("# Guide", encoding="utf-8")

    problems = _check_internal_links(tmp_path)
    assert problems == []


def test_internal_links_reference_definitions_broken(tmp_path: Path) -> None:
    """Broken reference-style links should be detected."""
    (tmp_path / "README.md").write_text(
        "See [Guide][guide].\n\n[guide]: missing.md\n",
        encoding="utf-8",
    )

    problems = _check_internal_links(tmp_path)
    assert len(problems) == 1
    assert "missing.md" in problems[0]["target"]
