exclude_dirs:
  - tools/tests
  - autopsy/tests
  - .venv
  - venv
  - env
  - __pycache__
  - .git
  - .pytest_cache
  - .tox
  - node_modules
  - build
  - dist
skips:
  - B101
  - B404  # subprocess import is intentional and wrapped via safe_subprocess where needed
  - B603  # subprocess without shell=True; inputs are controlled/validated
  - B310  # network calls validate scheme/host explicitly
